[package]
name = "tomato"
version = "0.0.0"
description = "A test project for Buffy"
license = "MIT"
authors = [
  { name = "Julian Siebert", email = "mail@julian-siebert.de" },
]

[golang]
module = "github.com/julian-siebert/tomato-go"
remote = "git@github.com:julian-siebert/tomato-go.git"
branch = "main"

[rust]
name     = "tomato-proto"
registry = "crates-io"
documentation = "https://github.com/julian-siebert/tomato"
homepage = "https://github.com/julian-siebert/tomato"
repository = "https://github.com/julian-siebert/tomato"

# ── Java ──────────────────────────────────────────────────────────────────────
# [java]
# group_id    = "com.your-org"
# artifact_id = "{name}-proto"
# description = "Generated protobuf stubs for {name}"
# url         = "https://github.com/your-org/{name}"
#
# [java.license]
# name = "Apache-2.0"
# url  = "https://www.apache.org/licenses/LICENSE-2.0"
#
# [java.developer]
# id    = "your-bot"
# name  = "Your Name"
# email = "you@your-org.com"
#
# [java.scm]
# connection = "scm:git:git://github.com/your-org/{name}.git"
# url        = "https://github.com/your-org/{name}"
